### ISSUE TITLE
Compilation of QD branch without KD-tree

### ISSUE THREAD

**Issue by jbmouret** [sferes2/sferes2#104]
It currently fails
```
../examples/ex_qd.cpp:147:28: error: 'KdtreeStorage' in namespace 'sferes::qd::container' does not name a template type
     typedef qd::container::KdtreeStorage< boost::shared_ptr<phen_t>, Params::qd::behav_dim > storage_t;
```

**Comment by Aneoshun** [comment]
The reason is that this line should be commented out: https://github.com/sferes2/sferes2/blob/e4aa73331f02e3eb926a4508a9843d227e0cb5a2/examples/ex_qd.cpp#L147
and the sort-based archive should be used instead (just the line below).

**Comment by Aneoshun** [comment]
I have updated the example to make it compile. If that works on your side, you can close the issue.

**Comment by jbmouret** [comment]
Works for me. Thanks.
