### ISSUE TITLE
Population size needs to be a multiple of 4 for NSGAII

### ISSUE THREAD

**Issue by vassilisvas** [sferes2/sferes2#32]
Population sizes that are not a multiple of 4 stop the execution of the program (either produce a segmentation fault, a bus error or something else).

The way tournament selection is implemented is causing that (https://github.com/sferes2/sferes2/blob/novelty_stats/sferes/ea/nsga2.hpp#L208), but I guess this is the way it was proposed by Deb (?)

What do you think we should do about this issue?

**Comment by jbmouret** [comment]
There is an assert but assert a deactivated in the non-debug version (which
is not compiled by default with the new waf). I would say that we should
probably activate the assert by default (i.e. remove the -DNDEBUG flag) and
have an explicit no-assert flag.
