### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Instassa** [sferes2/sferes2#38]
I am trying to install Sferes2 + collectball. My Ubuntu version is 14.04, running on VirtualBox.
Getting an error as in this attached document: [ErrorMessage_sferes2.docx](https://github.com/sferes2/sferes2/files/286285/ErrorMessage_sferes2.docx)

Terminal input is precisely the following (installing from scratch):
`sudo apt-get install build-essential
sudo apt-get install libboost-dev libboost-test-dev libboost-filesystem-dev libboost-program-options-dev libboost-graph-parallel-dev python g++ libtbb-dev libeigen3-dev python-simplejson libgoogle-perftools-dev

mkdir git
cd git
git clone https://github.com/sferes2/sferes2
git clone https://github.com/sferes2/fastsim
git clone https://github.com/sferes2/nn2
git clone https://github.com/jbmouret/libfastsim
git clone https://github.com/doncieux/collectball

cd ~/git/libfastsim
./waf configure
./waf build

cd ~/git/sferes2/modules
ln -s ~/git/fastsim
ln -s ~/git/nn2
cd ~/git/sferes2/exp
ln -s ~/git/collectball
cd ~/git/sferes2/
echo fastsim >> modules.conf
echo nn2 >> modules.conf

cd ~/git/sferes2
./waf configure
./waf build --exp=collectball
`

When I replace the ./waf configure in the end with ./waf configuration –boost-includes=BOOSTINCLUDES –boost-libs=BOOSTLIBS, I get the this error:
![screenshot from 2016-05-19 17 19 07](https://cloud.githubusercontent.com/assets/12833628/15605831/51fe0ef4-2400-11e6-88c7-a52d55b4d5fc.png)

And declaring C++11 flags during the configuration gives the following errors:
![2](https://cloud.githubusercontent.com/assets/12833628/15605868/99824de4-2400-11e6-8cd6-9b226bc4d31a.png)
![3](https://cloud.githubusercontent.com/assets/12833628/15605873/a191f782-2400-11e6-9025-c92bac5140b3.png)

**Comment by jbmouret** [comment]
I think the collectball experiments have not been updated to work with the
last sferes version. @doncieux ? One solution is to go back to the previous
version (e.g. master 3 months ago). Or @doncieux can update the wscript.

**Comment by jbmouret** [comment]
Closed because no news.
