### ISSUE TITLE
Failed in running the unit tests 

### ISSUE THREAD

**Issue by MiaoqiangSu** [sferes2/sferes2#39]
**Hi  jbmouret,
  The terminal shows the following errors when I do the  ./waf check. These commands are done under Ubuntu 14.04 LTS. Thanks in advance!**
module : [modules/nn2]
module : [modules/map_elite]
Waf: Entering directory `/home/sferes/build'
Entering directory `/home/sferes'
Entering directory `/home/sferes/modules/'
Entering directory `/home/sferes/modules/'
Waf: Leaving directory `/home/sferes/build'
'build' finished successfully (0.005s)
Running the unit tests 
default/tests/tests_modif_diversity .........ERROR 
default/tests/tests_eval_parallel ...........ERROR 
default/tests/tests_eval_mpi ................ERROR 
default/tests/tests_ea_cmaes ................ERROR 
default/tests/tests_ea_nsga2 ................ERROR 
default/tests/tests_ea_eps_moea .............ERROR 
default/tests/tests_ea_rank_simple ..........ERROR 
default/tests/tests_ea_dom_sort .............ERROR 
default/tests/tests_gen_cmaes ...............ERROR 
default/tests/tests_gen_bit_string ..........ERROR 
default/tests/tests_gen_evo_float ...........ERROR 
default/tests/tests_gen_sampled .............ERROR 
default/modules/nn2/test_nn .................ERROR 
default/modules/nn2/test_dnn ................ERROR 
default/modules/nn2/test_mlp ................ERROR 
default/modules/nn2/test_hyper_nn ...........ERROR 
default/modules/nn2/test_dnn_ff .............ERROR 
default/modules/nn2/test_osc ................ERROR 
default/modules/nn2/test_hyper_nn_anh .......ERROR 
default/modules/map_elite/test_map_elite ....ERROR 
debug/tests/tests_modif_diversity ...........ERROR 
debug/tests/tests_eval_parallel .............ERROR 
debug/tests/tests_eval_mpi ..................ERROR 
debug/tests/tests_ea_cmaes ..................ERROR 
debug/tests/tests_ea_nsga2 ..................ERROR 
debug/tests/tests_ea_eps_moea ...............ERROR 
debug/tests/tests_ea_rank_simple ............ERROR 
debug/tests/tests_ea_dom_sort ...............ERROR 
debug/tests/tests_gen_cmaes .................ERROR 
debug/tests/tests_gen_bit_string ............ERROR 
debug/tests/tests_gen_evo_float .............ERROR 
debug/tests/tests_gen_sampled ...............ERROR 
debug/modules/nn2/test_nn ...................ERROR 
debug/modules/nn2/test_dnn ..................ERROR 
debug/modules/nn2/test_mlp ..................ERROR 
debug/modules/nn2/test_hyper_nn .............ERROR 
debug/modules/nn2/test_dnn_ff ...............ERROR 
debug/modules/nn2/test_osc ..................ERROR 
debug/modules/nn2/test_hyper_nn_anh .........ERROR 
debug/modules/map_elite/test_map_elite ......ERROR 

Successful tests:      0 (0.0%)
Failed tests:          0 (0.0%)
Erroneous tests:       40 (100.0%)

Total number of tests: 40
 
Unit tests finished 
'check' finished successfully (0.094s)

  **Before this, I did ./waf configure, and the terminal returns:**

module : [modules/nn2]
module : [modules/map_elite]
Check for program g++ or c++             : /usr/bin/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Checking for g++                         : ok  
boost headers                            : Version 1_54 (/usr/include) 
library boost_serialization              : not found 
library boost_filesystem                 : not found 
library boost_system                     : not found 
library boost_unit_test_framework        : not found 
library boost_program_options            : not found 
library boost_graph                      : not found 
library boost_mpi                        : not found 
library boost_python                     : not found 
library boost_thread                     : not found 
Checking for header tbb/parallel_for.h   : ok /usr/include 
Checking for library libtbb              : ok /usr/lib 
Checking for header tbb/parallel_for.h   : ok /usr/include 
Checking for library libtbb              : ok /usr/lib 
Checking for header mpi.h                : ok /usr/include/mpi 
Checking for SDL (optional)              : not found 
Checking for header Eigen/Core           : ok /usr/include/eigen3 
Check for program ode-config             : not found 
Checking for ODE (optional)              : not found 
Checking for GSL (optional)              : not found 

--- configuration ---
compiler:
 * CXX: gcc
boost version: 1_54
mpi: False
Compilation flags :
 * default:
   CXXFLAGS : -D_REENTRANT -Wall -fPIC -ftemplate-depth-1024 -Wno-sign-compare -Wno-deprecated  -Wno-unused -DEIGEN3_ENABLED -DSFERES_ROOT="/home/sferes"  -DNDEBUG -O3 -ffast-math 
   LINKFLAGS: 
 * debug:
   CXXFLAGS : -D_REENTRANT -Wall -fPIC -ftemplate-depth-1024 -Wno-sign-compare -Wno-deprecated  -Wno-unused -DEIGEN3_ENABLED -DSFERES_ROOT="/home/sferes" -O1 -ggdb3 -DDBG_ENABLED 
   LINKFLAGS: 
 
--- license ---
Sferes2 is distributed under the CECILL license (GPL-compatible)
Please check the accompagnying COPYING file or http://www.cecill.info/
'configure' finished successfully (0.154s)

  **And ./waf build returns:**

./waf buildmodule : [modules/nn2]
module : [modules/map_elite]
Waf: Entering directory `/home/sferes/build'
Entering directory `/home/sferes'
Entering directory `/home/sferes/modules/'
Entering directory `/home/sferes/modules/'
Waf: Leaving directory `/home/sferes/build'
'build' finished successfully (0.019s)

**Comment by jbmouret** [comment]
Sferes did not find the boost libraries (libboost*.so). You can fix it by
adding ```--boost-libs=the_path_to_your_boost_libaries``` when doing
```./waf configure```

**Comment by MiaoqiangSu** [comment]
Thanks for your reply. However, when doing "./waf configure ----boost-libs=/usr/lib/x86_64-linux-gnu", the terminal returns:

`module : [modules/nn2]
module : [modules/map_elite]
Check for program g++ or c++             : /usr/bin/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Checking for g++                         : ok  
boost headers                            : Version 1_54 (/usr/include) 
library boost_serialization              : ok 
library boost_filesystem                 : ok 
library boost_system                     : ok 
library boost_unit_test_framework        : ok 
library boost_program_options            : ok 
library boost_graph                      : ok 
library boost_mpi                        : ok 
library boost_python                     : ok 
library boost_thread                     : ok 
Checking for header tbb/parallel_for.h   : ok /usr/include 
Checking for library libtbb              : ok /usr/lib 
Checking for header tbb/parallel_for.h   : ok /usr/include 
Checking for library libtbb              : ok /usr/lib 
Checking for header mpi.h                : ok /usr/include/mpi 
Checking for SDL (optional)              : not found 
Checking for header Eigen/Core           : ok /usr/include/eigen3 
Check for program ode-config             : not found 
Checking for ODE (optional)              : not found 
Checking for GSL (optional)              : not found 
`
And the errors still exist when I tried to do the "./waf check". The same problem even when I tried "ln -s  /usr/lib/x86_64-linux-gnu/libboost* ."
