### ISSUE TITLE
Building with --no-mpi still requires boost mpi

### ISSUE THREAD

**Issue by JoostHuizinga** [sferes2/sferes2#43]
On a system where boost mpi is not installed, configuring sferes with the option --no-mpi fails with the following message:

```
Checking boost libs                      : lib mpi not found in lib
(complete log in /Users/joost/Documents/sferes/sferes2/build/config.log)
```

I have currently resolved the issue by changing the following code in the wscript file in the sferes root folder:

Original code:
`conf.check_boost(lib='serialization filesystem system unit_test_framework program_options graph mpi thread regex', min_version='1.35')`

My 'fix':

```
    if conf.options.no_mpi:
        conf.check_boost(lib='serialization filesystem system unit_test_framework program_options graph thread regex', min_version='1.35')
    else:
        conf.check_boost(lib='serialization filesystem system unit_test_framework program_options graph mpi thread regex', min_version='1.35')
```

However, I am not sure if this is the most elegant way of doing things, especially because the --no-mpi option is part of the mpi.py modules, and not part of the basic wscript.

**Comment by costashatz** [comment]
Fixed in #55 ...
