### ISSUE TITLE
ea.stat() is only available in const version

### ISSUE THREAD

**Issue by JoostHuizinga** [sferes2/sferes2#47]
Okay, this will be the last issue I will submit for the day.

Is there a reason why the `ea.stat()` method is only available as a const version? Currently, I am only modifying the stat object in my (hopefully) obsolete continue module, but I wondered if there was any particular reason why I shouldn't.  If not, I would suggest adding a non-cont `ea.stat()` method, just to provide users more freedom when designing algorithms or modules.

By the way, I would be happy to fix some of these issues myself (provided that they are actually issues that need to be fixed), and do a pull request.

**Comment by costashatz** [comment]
@jbmouret is there any reason why would you have objection of making `ea.stat()` non-const?

**Comment by jbmouret** [comment]
In theory, stats should be pure observers that are queried, therefore they
should be const. Modifiers are very similar are can modify / be modified.

However, it makes things easier, a we can add a non const version of stat().

**Comment by JoostHuizinga** [comment]
I can see why that would be a good idea. I guess the only reason why I try to modify them is because I am also using these stat objects to determine what is written to (different) gen files.

Maybe there are better ways to write loadable gen files then what I am doing now.
