### ISSUE TITLE
Feature request: automatic detection of libraries loaded through modules

### ISSUE THREAD

**Issue by JoostHuizinga** [sferes2/sferes2#51]
Most clusters I know of use the Lmod package to allow user to load different libraries and different versions of those libraries. However, while Sferes is designed to run on clusters and other parallel environments, it is generally unable to find libraries loaded through modules, and users will have to specify include paths and library paths manually.

While a system that can detect any module on any cluster may be difficult to create, I think we can go a long way by simply checking the `CPPFLAGS` and `LD_LIBRARY_PATH` environment variables, both of which are set by Lmod on Mount Moran (the University of Wyoming cluster). 

Finding 'MPI' is a little bit harder (you are supposed to rely on the mpicxx wrapper compiler to handle these includes for you), but by checking the environment variables for MPI_ROOT and I_MPI_ROOT, we can at least provide some 'best effort' detection.

I have already implement this kind of detection for `boost.py`, `mpi.py`, `eigen.py`, and `tbb.py`, in case you are interested.

**Comment by jbmouret** [comment]
We do not have Lmod on our cluster(s) therefore it will be hard for us to test this. If you have an implementation, can you do a PR? Thanks!

**Comment by costashatz** [comment]
I think this is solved in #54 ... **Closing**
