### ISSUE TITLE
Problems with compiling

### ISSUE THREAD

**Issue by vlnguyen92** [sferes2/sferes2#59]
I follow the instructions here: https://github.com/sferes2/sferes2/wiki/Compilation

After installing all the dependencies, I ran `./waf configure`. The error is:

```
Checking boost libs                      : lib thread not found in x86_64-linux-gnu
```

Has somebody encountered this before?

**Comment by costashatz** [comment]
You need to install the boost thread library: `sudo apt-get install libboost-thread-dev`

**Comment by jbmouret** [comment]
closed because no news.

**Comment by Nicholas-J-Sabaj** [comment]
Just wanted to note that **sudo apt-get install libboost-all-dev** also fixed the same problem for me; it might be prudent to change the initial instructions to include this.
