### ISSUE TITLE
Getter methods for population in NSGA2 seem to be missing const declaration

### ISSUE THREAD

**Issue by JoostHuizinga** [sferes2/sferes2#67]
In the NSGA2 implementation provided with Sferes (sferes/ea/nsga2.hpp) the mixed_pop, parent_pop, and child_pop methods have a const return type, but the methods themselves are not declared as constant. This is inconvenient, especially when considering that the refresh method in sferes/stat/stat.hpp declares the ea as constant (`void refresh(const E& ea)`), meaning these populations can not be accessed in the stat refresh method, even if we do not actually change anything about these populations. 

As such, I want to propose the following change, from:

      const pop_t& mixed_pop() {
        return _mixed_pop;
      }
      const pop_t& parent_pop() {
        return _parent_pop;
      }
      const pop_t& child_pop() {
        return _child_pop;
      }

To:

      const pop_t& mixed_pop() const {
        return _mixed_pop;
      }
      const pop_t& parent_pop() const {
        return _parent_pop;
      }
      const pop_t& child_pop() const {
        return _child_pop;
      }

**Comment by jbmouret** [comment]
Good catch. Can you make a pull request?

**Comment by jbmouret** [comment]
Fixed in #70
