### ISSUE TITLE
Segmentation fault using eval::Parallel

### ISSUE THREAD

**Issue by daneshtarapore** [sferes2/sferes2#99]
Hi,

I am struggling with an issue using eval::Parallel in a sferes code with nn2 phenotypes and would appreciate any insights you can provide. The project is part of an interface between sferes and a swarm-robotic simulation framework -- https://github.com/resilient-swarms/argos-sferes

While running sferes with eval::Eval works fine, eval::Parallel gives a segmentation fault. A backtrace of gdb output follows:

sferes2 version: (const char*)"f731bfb04a48a475dfedbfdb180d77054498557f"
seed: 1554138169
[New Thread 0x7fffd65e8700 (LWP 10166)]
[New Thread 0x7fffd61e7700 (LWP 10167)]
[New Thread 0x7fffd5de6700 (LWP 10168)]
[New Thread 0x7fffd51e3700 (LWP 10171)]
[New Thread 0x7fffd55e4700 (LWP 10169)]
[New Thread 0x7fffd59e5700 (LWP 10170)]
[New Thread 0x7fffd4de2700 (LWP 10172)]
free(): invalid pointer

Thread 1 "obsavoid_evol" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:308
308     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:308
#1  0x000055555578fc8e in float* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<float>(float const*, float const*, float*) ()
#2  0x000055555578d10f in float* std::__copy_move_a<false, float const*, float*>(float const*, float const*, float*) ()
#3  0x0000555555789ed7 in __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > > std::__copy_move_a2<false, __gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > > >(__gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >) ()
#4  0x0000555555786f95 in __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > > std::copy<__gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > > >(__gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >) ()
#5  0x00005555557835e9 in std::vector<float, std::allocator<float> >::operator=(std::vector<float, std::allocator<float> > const&) ()
#6  0x00005555557908e9 in sferes::gen::Float<1, ParamsDnn, sferes::gen::Float<1, ParamsDnn, stc::Itself> >::operator=(sferes::gen::Float<1, ParamsDnn, sferes::gen::Float<1, ParamsDnn, stc::Itself> > const&) ()
#7  0x0000555555790913 in sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>::operator=(sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself> const&) ()
#8  0x00005555557909b7 in sferes::phen::Indiv<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >::operator=(sferes::phen::Indiv<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> > const&) ()
#9  0x00005555557909fb in sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>::operator=(sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> const&) ()
#10 0x00005555557987f3 in nn::Pf<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, nn::params::Dummy>::set_weight(unsigned long, sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> const&) ()
#11 0x0000555555793d10 in nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>::set_weight(unsigned int, sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> const&) ()
#12 0x0000555555790f60 in nn::NN<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float> >::_init() ()
#13 0x000055555578e120 in nn::NN<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float> >::init() ()
#14 0x000055555579b39c in void sferes::FitObstacleMapElites<Params, stc::Itself>::eval<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >(sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself>&) ()
#15 0x00005555557ebc31 in sferes::eval::_parallel_evaluate<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >::operator()(tbb::blocked_range<unsigned long> const&) const ()
#16 0x00005555557ea541 in tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, sferes::eval::_parallel_evaluate<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >, tbb::auto_partitioner const>::run_body(tbb::blocked_range<unsigned long>&) ()
#17 0x00005555557e93ef in void tbb::interface9::internal::balancing_partition_type<tbb::interface9::internal::adaptive_mode<tbb::interface9::internal::auto_partition_type> >::work_balance<tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, sferes::eval::_parallel_evaluate<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >, tbb::auto_partitioner const>, tbb::blocked_range<unsigned long> >(tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, sferes::eval::_parallel_evaluate<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >, tbb::auto_partitioner const>&, tbb::blocked_range<unsigned long>&) ()
#18 0x00005555557e7e8a in void tbb::interface9::internal::partition_type_base<tbb::interface9::internal::auto_partition_type>::execute<tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, sferes::eval::_parallel_evaluate<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >, tbb::auto_partitioner const>, tbb::blocked_range<unsigned long> >(tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, sferes::eval::_parallel_evaluate<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >, tbb::auto_partitioner const>&, tbb::blocked_range<unsigned long>&) ()
#19 0x00005555557e58dc in tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, sferes::eval::_parallel_evaluate<sferes::phen::Dnn<sferes::gen::Dnn<nn::Neuron<nn::PfWSum<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, nn::AfTanh<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself> >, float>, nn::Connection<sferes::phen::Parameters<sferes::gen::EvoFloat<1, ParamsDnn, stc::Itself>, sferes::fit::FitDummy<stc::_Params, stc::Itself>, ParamsDnn, stc::Itself>, float>, ParamsDnn>, sferes::FitObstacleMapElites<Params, stc::Itself>, ParamsDnn, stc::Itself> >, tbb::auto_partitioner const>::execute() ()
#20 0x00007ffff6a56b46 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7fffe9c5fe00, parent=..., child=<optimised out>) at ../../src/tbb/custom_scheduler.h:501
#21 0x00007ffff6a53790 in tbb::internal::generic_scheduler::local_spawn_root_and_wait (this=0x7fffe9c5fe00, first=0x7fffe9cdef40, next=@0x7fffe9cdef38: 0x0) at ../../src/tbb/scheduler.cpp:677
#22 0x000055555577796b in tbb::task::spawn_root_and_wait(tbb::task&) ()

Am using TBB libs (version: 2017.0) for tbb, malloc and malloc_preview.   System configurations are:
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
Boost version: 1.65.1

Any ideas would be much appreciated.

Thanks,
Danesh.

**Comment by jbmouret** [comment]
@daneshtarapore I guess this is not a problem anymore? Most likely a problem in your fitness function.

**Comment by daneshtarapore** [comment]
Yes, it has been sorted. Thank you.
